spring.profiles.active: ${ACTIVE_PROFILE}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baselineOnMigrate: false
    validate-on-migrate: true
    validateMigrationNaming: true
    table: db_migration_history
    outOfOrder: true