spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fabhotel_skill_endorsement
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    datasource:
      initialization-mode: always

  flyway:
    enabled: false
    baselineOnMigrate: true
    validate-on-migrate: true
    validateMigrationNaming: true
    table: db_migration_history